/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing AlertingVstsBugtrackerSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlertingVstsBugtrackerSettingsTests
    {
        // TODO uncomment below to declare an instance variable for AlertingVstsBugtrackerSettings
        //private AlertingVstsBugtrackerSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlertingVstsBugtrackerSettings
            //instance = new AlertingVstsBugtrackerSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlertingVstsBugtrackerSettings
        /// </summary>
        [Test]
        public void AlertingVstsBugtrackerSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlertingVstsBugtrackerSettings
            //Assert.IsInstanceOfType<AlertingVstsBugtrackerSettings> (instance, "variable 'instance' is a AlertingVstsBugtrackerSettings");
        }


        /// <summary>
        /// Test the property 'VstsProjectId'
        /// </summary>
        [Test]
        public void VstsProjectIdTest()
        {
            // TODO unit test for the property 'VstsProjectId'
        }
        /// <summary>
        /// Test the property 'VstsProjectUri'
        /// </summary>
        [Test]
        public void VstsProjectUriTest()
        {
            // TODO unit test for the property 'VstsProjectUri'
        }
        /// <summary>
        /// Test the property 'VstsProjectName'
        /// </summary>
        [Test]
        public void VstsProjectNameTest()
        {
            // TODO unit test for the property 'VstsProjectName'
        }
        /// <summary>
        /// Test the property 'VstsAccountName'
        /// </summary>
        [Test]
        public void VstsAccountNameTest()
        {
            // TODO unit test for the property 'VstsAccountName'
        }
        /// <summary>
        /// Test the property 'VstsAreaPath'
        /// </summary>
        [Test]
        public void VstsAreaPathTest()
        {
            // TODO unit test for the property 'VstsAreaPath'
        }
        /// <summary>
        /// Test the property 'VstsDefaultPayload'
        /// </summary>
        [Test]
        public void VstsDefaultPayloadTest()
        {
            // TODO unit test for the property 'VstsDefaultPayload'
        }

    }

}
