/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing AlertingJiraBugtrackerSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AlertingJiraBugtrackerSettingsTests
    {
        // TODO uncomment below to declare an instance variable for AlertingJiraBugtrackerSettings
        //private AlertingJiraBugtrackerSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AlertingJiraBugtrackerSettings
            //instance = new AlertingJiraBugtrackerSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AlertingJiraBugtrackerSettings
        /// </summary>
        [Test]
        public void AlertingJiraBugtrackerSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AlertingJiraBugtrackerSettings
            //Assert.IsInstanceOfType<AlertingJiraBugtrackerSettings> (instance, "variable 'instance' is a AlertingJiraBugtrackerSettings");
        }


        /// <summary>
        /// Test the property 'JiraProjectId'
        /// </summary>
        [Test]
        public void JiraProjectIdTest()
        {
            // TODO unit test for the property 'JiraProjectId'
        }
        /// <summary>
        /// Test the property 'JiraProjectName'
        /// </summary>
        [Test]
        public void JiraProjectNameTest()
        {
            // TODO unit test for the property 'JiraProjectName'
        }

    }

}
