/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing AppleCertificateNonSecretDetailsResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppleCertificateNonSecretDetailsResponseDataTests
    {
        // TODO uncomment below to declare an instance variable for AppleCertificateNonSecretDetailsResponseData
        //private AppleCertificateNonSecretDetailsResponseData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppleCertificateNonSecretDetailsResponseData
            //instance = new AppleCertificateNonSecretDetailsResponseData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppleCertificateNonSecretDetailsResponseData
        /// </summary>
        [Test]
        public void AppleCertificateNonSecretDetailsResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppleCertificateNonSecretDetailsResponseData
            //Assert.IsInstanceOfType<AppleCertificateNonSecretDetailsResponseData> (instance, "variable 'instance' is a AppleCertificateNonSecretDetailsResponseData");
        }


        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'CertificateValidityStartDate'
        /// </summary>
        [Test]
        public void CertificateValidityStartDateTest()
        {
            // TODO unit test for the property 'CertificateValidityStartDate'
        }
        /// <summary>
        /// Test the property 'CertificateValidityEndDate'
        /// </summary>
        [Test]
        public void CertificateValidityEndDateTest()
        {
            // TODO unit test for the property 'CertificateValidityEndDate'
        }

    }

}
