/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing AppleCredentialsMultifactorSecretRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AppleCredentialsMultifactorSecretRequestTests
    {
        // TODO uncomment below to declare an instance variable for AppleCredentialsMultifactorSecretRequest
        //private AppleCredentialsMultifactorSecretRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppleCredentialsMultifactorSecretRequest
            //instance = new AppleCredentialsMultifactorSecretRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppleCredentialsMultifactorSecretRequest
        /// </summary>
        [Test]
        public void AppleCredentialsMultifactorSecretRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppleCredentialsMultifactorSecretRequest
            //Assert.IsInstanceOfType<AppleCredentialsMultifactorSecretRequest> (instance, "variable 'instance' is a AppleCredentialsMultifactorSecretRequest");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
