/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing BranchStatusLastBuild
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BranchStatusLastBuildTests
    {
        // TODO uncomment below to declare an instance variable for BranchStatusLastBuild
        //private BranchStatusLastBuild instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BranchStatusLastBuild
            //instance = new BranchStatusLastBuild();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BranchStatusLastBuild
        /// </summary>
        [Test]
        public void BranchStatusLastBuildInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BranchStatusLastBuild
            //Assert.IsInstanceOfType<BranchStatusLastBuild> (instance, "variable 'instance' is a BranchStatusLastBuild");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'BuildNumber'
        /// </summary>
        [Test]
        public void BuildNumberTest()
        {
            // TODO unit test for the property 'BuildNumber'
        }
        /// <summary>
        /// Test the property 'QueueTime'
        /// </summary>
        [Test]
        public void QueueTimeTest()
        {
            // TODO unit test for the property 'QueueTime'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }
        /// <summary>
        /// Test the property 'FinishTime'
        /// </summary>
        [Test]
        public void FinishTimeTest()
        {
            // TODO unit test for the property 'FinishTime'
        }
        /// <summary>
        /// Test the property 'LastChangedDate'
        /// </summary>
        [Test]
        public void LastChangedDateTest()
        {
            // TODO unit test for the property 'LastChangedDate'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Result'
        /// </summary>
        [Test]
        public void ResultTest()
        {
            // TODO unit test for the property 'Result'
        }
        /// <summary>
        /// Test the property 'SourceBranch'
        /// </summary>
        [Test]
        public void SourceBranchTest()
        {
            // TODO unit test for the property 'SourceBranch'
        }
        /// <summary>
        /// Test the property 'SourceVersion'
        /// </summary>
        [Test]
        public void SourceVersionTest()
        {
            // TODO unit test for the property 'SourceVersion'
        }

    }

}
