/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing ErrorGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ErrorGroupTests
    {
        // TODO uncomment below to declare an instance variable for ErrorGroup
        //private ErrorGroup instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ErrorGroup
            //instance = new ErrorGroup();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ErrorGroup
        /// </summary>
        [Test]
        public void ErrorGroupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ErrorGroup
            //Assert.IsInstanceOfType<ErrorGroup> (instance, "variable 'instance' is a ErrorGroup");
        }


        /// <summary>
        /// Test the property 'ErrorGroupId'
        /// </summary>
        [Test]
        public void ErrorGroupIdTest()
        {
            // TODO unit test for the property 'ErrorGroupId'
        }
        /// <summary>
        /// Test the property 'AppVersion'
        /// </summary>
        [Test]
        public void AppVersionTest()
        {
            // TODO unit test for the property 'AppVersion'
        }
        /// <summary>
        /// Test the property 'AppBuild'
        /// </summary>
        [Test]
        public void AppBuildTest()
        {
            // TODO unit test for the property 'AppBuild'
        }
        /// <summary>
        /// Test the property 'Count'
        /// </summary>
        [Test]
        public void CountTest()
        {
            // TODO unit test for the property 'Count'
        }
        /// <summary>
        /// Test the property 'DeviceCount'
        /// </summary>
        [Test]
        public void DeviceCountTest()
        {
            // TODO unit test for the property 'DeviceCount'
        }
        /// <summary>
        /// Test the property 'FirstOccurrence'
        /// </summary>
        [Test]
        public void FirstOccurrenceTest()
        {
            // TODO unit test for the property 'FirstOccurrence'
        }
        /// <summary>
        /// Test the property 'LastOccurrence'
        /// </summary>
        [Test]
        public void LastOccurrenceTest()
        {
            // TODO unit test for the property 'LastOccurrence'
        }
        /// <summary>
        /// Test the property 'ExceptionType'
        /// </summary>
        [Test]
        public void ExceptionTypeTest()
        {
            // TODO unit test for the property 'ExceptionType'
        }
        /// <summary>
        /// Test the property 'ExceptionMessage'
        /// </summary>
        [Test]
        public void ExceptionMessageTest()
        {
            // TODO unit test for the property 'ExceptionMessage'
        }
        /// <summary>
        /// Test the property 'ExceptionClassName'
        /// </summary>
        [Test]
        public void ExceptionClassNameTest()
        {
            // TODO unit test for the property 'ExceptionClassName'
        }
        /// <summary>
        /// Test the property 'ExceptionClassMethod'
        /// </summary>
        [Test]
        public void ExceptionClassMethodTest()
        {
            // TODO unit test for the property 'ExceptionClassMethod'
        }
        /// <summary>
        /// Test the property 'ExceptionMethod'
        /// </summary>
        [Test]
        public void ExceptionMethodTest()
        {
            // TODO unit test for the property 'ExceptionMethod'
        }
        /// <summary>
        /// Test the property 'ExceptionAppCode'
        /// </summary>
        [Test]
        public void ExceptionAppCodeTest()
        {
            // TODO unit test for the property 'ExceptionAppCode'
        }
        /// <summary>
        /// Test the property 'ExceptionFile'
        /// </summary>
        [Test]
        public void ExceptionFileTest()
        {
            // TODO unit test for the property 'ExceptionFile'
        }
        /// <summary>
        /// Test the property 'ExceptionLine'
        /// </summary>
        [Test]
        public void ExceptionLineTest()
        {
            // TODO unit test for the property 'ExceptionLine'
        }
        /// <summary>
        /// Test the property 'CodeRaw'
        /// </summary>
        [Test]
        public void CodeRawTest()
        {
            // TODO unit test for the property 'CodeRaw'
        }
        /// <summary>
        /// Test the property 'ReasonFrames'
        /// </summary>
        [Test]
        public void ReasonFramesTest()
        {
            // TODO unit test for the property 'ReasonFrames'
        }
        /// <summary>
        /// Test the property 'Hidden'
        /// </summary>
        [Test]
        public void HiddenTest()
        {
            // TODO unit test for the property 'Hidden'
        }

    }

}
