/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing AppCenterException
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ExceptionTests
    {
        // TODO uncomment below to declare an instance variable for AppCenterException
        //private AppCenterException instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AppCenterException
            //instance = new AppCenterException();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AppCenterException
        /// </summary>
        [Test]
        public void ExceptionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AppCenterException
            //Assert.IsInstanceOfType<AppCenterException> (instance, "variable 'instance' is a AppCenterException");
        }


        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Test]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Frames'
        /// </summary>
        [Test]
        public void FramesTest()
        {
            // TODO unit test for the property 'Frames'
        }
        /// <summary>
        /// Test the property 'Relevant'
        /// </summary>
        [Test]
        public void RelevantTest()
        {
            // TODO unit test for the property 'Relevant'
        }
        /// <summary>
        /// Test the property 'InnerExceptions'
        /// </summary>
        [Test]
        public void InnerExceptionsTest()
        {
            // TODO unit test for the property 'InnerExceptions'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Test]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

    }

}
