/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing GooglePlayConnectionSecretResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GooglePlayConnectionSecretResponseTests
    {
        // TODO uncomment below to declare an instance variable for GooglePlayConnectionSecretResponse
        //private GooglePlayConnectionSecretResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GooglePlayConnectionSecretResponse
            //instance = new GooglePlayConnectionSecretResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GooglePlayConnectionSecretResponse
        /// </summary>
        [Test]
        public void GooglePlayConnectionSecretResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GooglePlayConnectionSecretResponse
            //Assert.IsInstanceOfType<GooglePlayConnectionSecretResponse> (instance, "variable 'instance' is a GooglePlayConnectionSecretResponse");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
