/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing HandledErrorDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class HandledErrorDetailsTests
    {
        // TODO uncomment below to declare an instance variable for HandledErrorDetails
        //private HandledErrorDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of HandledErrorDetails
            //instance = new HandledErrorDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of HandledErrorDetails
        /// </summary>
        [Test]
        public void HandledErrorDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" HandledErrorDetails
            //Assert.IsInstanceOfType<HandledErrorDetails> (instance, "variable 'instance' is a HandledErrorDetails");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ReasonFrames'
        /// </summary>
        [Test]
        public void ReasonFramesTest()
        {
            // TODO unit test for the property 'ReasonFrames'
        }
        /// <summary>
        /// Test the property 'AppLaunchTimestamp'
        /// </summary>
        [Test]
        public void AppLaunchTimestampTest()
        {
            // TODO unit test for the property 'AppLaunchTimestamp'
        }
        /// <summary>
        /// Test the property 'CarrierName'
        /// </summary>
        [Test]
        public void CarrierNameTest()
        {
            // TODO unit test for the property 'CarrierName'
        }
        /// <summary>
        /// Test the property 'Jailbreak'
        /// </summary>
        [Test]
        public void JailbreakTest()
        {
            // TODO unit test for the property 'Jailbreak'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Test]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }

    }

}
