/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing JiraConnectionSecretResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JiraConnectionSecretResponseDataTests
    {
        // TODO uncomment below to declare an instance variable for JiraConnectionSecretResponseData
        //private JiraConnectionSecretResponseData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JiraConnectionSecretResponseData
            //instance = new JiraConnectionSecretResponseData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JiraConnectionSecretResponseData
        /// </summary>
        [Test]
        public void JiraConnectionSecretResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JiraConnectionSecretResponseData
            //Assert.IsInstanceOfType<JiraConnectionSecretResponseData> (instance, "variable 'instance' is a JiraConnectionSecretResponseData");
        }


        /// <summary>
        /// Test the property 'BaseUrl'
        /// </summary>
        [Test]
        public void BaseUrlTest()
        {
            // TODO unit test for the property 'BaseUrl'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
