/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing JiraCredentialNonSecretDetailsResponseData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class JiraCredentialNonSecretDetailsResponseDataTests
    {
        // TODO uncomment below to declare an instance variable for JiraCredentialNonSecretDetailsResponseData
        //private JiraCredentialNonSecretDetailsResponseData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of JiraCredentialNonSecretDetailsResponseData
            //instance = new JiraCredentialNonSecretDetailsResponseData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of JiraCredentialNonSecretDetailsResponseData
        /// </summary>
        [Test]
        public void JiraCredentialNonSecretDetailsResponseDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" JiraCredentialNonSecretDetailsResponseData
            //Assert.IsInstanceOfType<JiraCredentialNonSecretDetailsResponseData> (instance, "variable 'instance' is a JiraCredentialNonSecretDetailsResponseData");
        }


        /// <summary>
        /// Test the property 'BaseUrl'
        /// </summary>
        [Test]
        public void BaseUrlTest()
        {
            // TODO unit test for the property 'BaseUrl'
        }
        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Test]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

    }

}
