/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing LogFlowStartSessionLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LogFlowStartSessionLogTests
    {
        // TODO uncomment below to declare an instance variable for LogFlowStartSessionLog
        //private LogFlowStartSessionLog instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LogFlowStartSessionLog
            //instance = new LogFlowStartSessionLog();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LogFlowStartSessionLog
        /// </summary>
        [Test]
        public void LogFlowStartSessionLogInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LogFlowStartSessionLog
            //Assert.IsInstanceOfType<LogFlowStartSessionLog> (instance, "variable 'instance' is a LogFlowStartSessionLog");
        }


        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Test]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }

    }

}
