/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing LogFlowErrorLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LogFlowErrorLogTests
    {
        // TODO uncomment below to declare an instance variable for LogFlowErrorLog
        //private LogFlowErrorLog instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LogFlowErrorLog
            //instance = new LogFlowErrorLog();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LogFlowErrorLog
        /// </summary>
        [Test]
        public void LogFlowErrorLogInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LogFlowErrorLog
            //Assert.IsInstanceOfType<LogFlowErrorLog> (instance, "variable 'instance' is a LogFlowErrorLog");
        }


        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Test]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AppLaunchToffset'
        /// </summary>
        [Test]
        public void AppLaunchToffsetTest()
        {
            // TODO unit test for the property 'AppLaunchToffset'
        }

    }

}
