/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing RepoConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RepoConfigTests
    {
        // TODO uncomment below to declare an instance variable for RepoConfig
        //private RepoConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RepoConfig
            //instance = new RepoConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RepoConfig
        /// </summary>
        [Test]
        public void RepoConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RepoConfig
            //Assert.IsInstanceOfType<RepoConfig> (instance, "variable 'instance' is a RepoConfig");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'UserEmail'
        /// </summary>
        [Test]
        public void UserEmailTest()
        {
            // TODO unit test for the property 'UserEmail'
        }

    }

}
