/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing ToolsetsXamarin
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ToolsetsXamarinTests
    {
        // TODO uncomment below to declare an instance variable for ToolsetsXamarin
        //private ToolsetsXamarin instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ToolsetsXamarin
            //instance = new ToolsetsXamarin();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ToolsetsXamarin
        /// </summary>
        [Test]
        public void ToolsetsXamarinInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ToolsetsXamarin
            //Assert.IsInstanceOfType<ToolsetsXamarin> (instance, "variable 'instance' is a ToolsetsXamarin");
        }


        /// <summary>
        /// Test the property 'MonoVersion'
        /// </summary>
        [Test]
        public void MonoVersionTest()
        {
            // TODO unit test for the property 'MonoVersion'
        }
        /// <summary>
        /// Test the property 'SdkBundle'
        /// </summary>
        [Test]
        public void SdkBundleTest()
        {
            // TODO unit test for the property 'SdkBundle'
        }
        /// <summary>
        /// Test the property 'Current'
        /// </summary>
        [Test]
        public void CurrentTest()
        {
            // TODO unit test for the property 'Current'
        }
        /// <summary>
        /// Test the property 'Stable'
        /// </summary>
        [Test]
        public void StableTest()
        {
            // TODO unit test for the property 'Stable'
        }
        /// <summary>
        /// Test the property 'XcodeVersions'
        /// </summary>
        [Test]
        public void XcodeVersionsTest()
        {
            // TODO unit test for the property 'XcodeVersions'
        }

    }

}
