/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing V01appsownerNameappNameanalyticscrashGroupsOverall
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V01appsownerNameappNameanalyticscrashGroupsOverallTests
    {
        // TODO uncomment below to declare an instance variable for V01appsownerNameappNameanalyticscrashGroupsOverall
        //private V01appsownerNameappNameanalyticscrashGroupsOverall instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V01appsownerNameappNameanalyticscrashGroupsOverall
            //instance = new V01appsownerNameappNameanalyticscrashGroupsOverall();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V01appsownerNameappNameanalyticscrashGroupsOverall
        /// </summary>
        [Test]
        public void V01appsownerNameappNameanalyticscrashGroupsOverallInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V01appsownerNameappNameanalyticscrashGroupsOverall
            //Assert.IsInstanceOfType<V01appsownerNameappNameanalyticscrashGroupsOverall> (instance, "variable 'instance' is a V01appsownerNameappNameanalyticscrashGroupsOverall");
        }


        /// <summary>
        /// Test the property 'CrashCount'
        /// </summary>
        [Test]
        public void CrashCountTest()
        {
            // TODO unit test for the property 'CrashCount'
        }
        /// <summary>
        /// Test the property 'DeviceCount'
        /// </summary>
        [Test]
        public void DeviceCountTest()
        {
            // TODO unit test for the property 'DeviceCount'
        }

    }

}
