/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing V01orgsorgNamedistributionGroupsdistributionGroupNameappsApps
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V01orgsorgNamedistributionGroupsdistributionGroupNameappsAppsTests
    {
        // TODO uncomment below to declare an instance variable for V01orgsorgNamedistributionGroupsdistributionGroupNameappsApps
        //private V01orgsorgNamedistributionGroupsdistributionGroupNameappsApps instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V01orgsorgNamedistributionGroupsdistributionGroupNameappsApps
            //instance = new V01orgsorgNamedistributionGroupsdistributionGroupNameappsApps();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V01orgsorgNamedistributionGroupsdistributionGroupNameappsApps
        /// </summary>
        [Test]
        public void V01orgsorgNamedistributionGroupsdistributionGroupNameappsAppsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V01orgsorgNamedistributionGroupsdistributionGroupNameappsApps
            //Assert.IsInstanceOfType<V01orgsorgNamedistributionGroupsdistributionGroupNameappsApps> (instance, "variable 'instance' is a V01orgsorgNamedistributionGroupsdistributionGroupNameappsApps");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

    }

}
