/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using AppCenterApiClientLib.Api;
using AppCenterApiClientLib.Model;
using AppCenterApiClientLib.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace AppCenterApiClientLib.Test
{
    /// <summary>
    ///  Class for testing V2MissingSymbolCrashGroupMissingSymbols
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class V2MissingSymbolCrashGroupMissingSymbolsTests
    {
        // TODO uncomment below to declare an instance variable for V2MissingSymbolCrashGroupMissingSymbols
        //private V2MissingSymbolCrashGroupMissingSymbols instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of V2MissingSymbolCrashGroupMissingSymbols
            //instance = new V2MissingSymbolCrashGroupMissingSymbols();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of V2MissingSymbolCrashGroupMissingSymbols
        /// </summary>
        [Test]
        public void V2MissingSymbolCrashGroupMissingSymbolsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" V2MissingSymbolCrashGroupMissingSymbols
            //Assert.IsInstanceOfType<V2MissingSymbolCrashGroupMissingSymbols> (instance, "variable 'instance' is a V2MissingSymbolCrashGroupMissingSymbols");
        }


        /// <summary>
        /// Test the property 'SymbolId'
        /// </summary>
        [Test]
        public void SymbolIdTest()
        {
            // TODO unit test for the property 'SymbolId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Test]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
