/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = AppCenterApiClientLib.Client.SwaggerDateConverter;

namespace AppCenterApiClientLib.Model
{
    /// <summary>
    /// Jira bugtracker specific settings
    /// </summary>
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
        public partial class AlertingJiraBugtrackerSettings :  IEquatable<AlertingJiraBugtrackerSettings>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlertingJiraBugtrackerSettings" /> class.
        /// </summary>
        /// <param name="jiraProjectId">jiraProjectId.</param>
        /// <param name="jiraProjectName">jiraProjectName.</param>
        public AlertingJiraBugtrackerSettings(int? jiraProjectId = default(int?), string jiraProjectName = default(string))
        {
            this.JiraProjectId = jiraProjectId;
            this.JiraProjectName = jiraProjectName;
        }
        
        /// <summary>
        /// Gets or Sets JiraProjectId
        /// </summary>
        [DataMember(Name="jira_project_id", EmitDefaultValue=false)]
        public int? JiraProjectId { get; set; }

        /// <summary>
        /// Gets or Sets JiraProjectName
        /// </summary>
        [DataMember(Name="jira_project_name", EmitDefaultValue=false)]
        public string JiraProjectName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AlertingJiraBugtrackerSettings {\n");
            sb.Append("  JiraProjectId: ").Append(JiraProjectId).Append("\n");
            sb.Append("  JiraProjectName: ").Append(JiraProjectName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AlertingJiraBugtrackerSettings);
        }

        /// <summary>
        /// Returns true if AlertingJiraBugtrackerSettings instances are equal
        /// </summary>
        /// <param name="input">Instance of AlertingJiraBugtrackerSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlertingJiraBugtrackerSettings input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.JiraProjectId == input.JiraProjectId ||
                    (this.JiraProjectId != null &&
                    this.JiraProjectId.Equals(input.JiraProjectId))
                ) && 
                (
                    this.JiraProjectName == input.JiraProjectName ||
                    (this.JiraProjectName != null &&
                    this.JiraProjectName.Equals(input.JiraProjectName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.JiraProjectId != null)
                    hashCode = hashCode * 59 + this.JiraProjectId.GetHashCode();
                if (this.JiraProjectName != null)
                    hashCode = hashCode * 59 + this.JiraProjectName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
