/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = AppCenterApiClientLib.Client.SwaggerDateConverter;

namespace AppCenterApiClientLib.Model
{
    /// <summary>
    /// Github bugtracker specific settings
    /// </summary>
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "Type")]
        public partial class AlertingGithubBugtrackerSettings :  IEquatable<AlertingGithubBugtrackerSettings>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AlertingGithubBugtrackerSettings" /> class.
        /// </summary>
        /// <param name="githubRepoId">githubRepoId.</param>
        /// <param name="githubRepoName">githubRepoName.</param>
        /// <param name="githubLabel">githubLabel.</param>
        public AlertingGithubBugtrackerSettings(int? githubRepoId = default(int?), string githubRepoName = default(string), string githubLabel = default(string))
        {
            this.GithubRepoId = githubRepoId;
            this.GithubRepoName = githubRepoName;
            this.GithubLabel = githubLabel;
        }
        
        /// <summary>
        /// Gets or Sets GithubRepoId
        /// </summary>
        [DataMember(Name="github_repo_id", EmitDefaultValue=false)]
        public int? GithubRepoId { get; set; }

        /// <summary>
        /// Gets or Sets GithubRepoName
        /// </summary>
        [DataMember(Name="github_repo_name", EmitDefaultValue=false)]
        public string GithubRepoName { get; set; }

        /// <summary>
        /// Gets or Sets GithubLabel
        /// </summary>
        [DataMember(Name="github_label", EmitDefaultValue=false)]
        public string GithubLabel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AlertingGithubBugtrackerSettings {\n");
            sb.Append("  GithubRepoId: ").Append(GithubRepoId).Append("\n");
            sb.Append("  GithubRepoName: ").Append(GithubRepoName).Append("\n");
            sb.Append("  GithubLabel: ").Append(GithubLabel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AlertingGithubBugtrackerSettings);
        }

        /// <summary>
        /// Returns true if AlertingGithubBugtrackerSettings instances are equal
        /// </summary>
        /// <param name="input">Instance of AlertingGithubBugtrackerSettings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AlertingGithubBugtrackerSettings input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GithubRepoId == input.GithubRepoId ||
                    (this.GithubRepoId != null &&
                    this.GithubRepoId.Equals(input.GithubRepoId))
                ) && 
                (
                    this.GithubRepoName == input.GithubRepoName ||
                    (this.GithubRepoName != null &&
                    this.GithubRepoName.Equals(input.GithubRepoName))
                ) && 
                (
                    this.GithubLabel == input.GithubLabel ||
                    (this.GithubLabel != null &&
                    this.GithubLabel.Equals(input.GithubLabel))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GithubRepoId != null)
                    hashCode = hashCode * 59 + this.GithubRepoId.GetHashCode();
                if (this.GithubRepoName != null)
                    hashCode = hashCode * 59 + this.GithubRepoName.GetHashCode();
                if (this.GithubLabel != null)
                    hashCode = hashCode * 59 + this.GithubLabel.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
