/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = AppCenterApiClientLib.Client.SwaggerDateConverter;

namespace AppCenterApiClientLib.Model
{
    /// <summary>
    /// apple secret details
    /// </summary>
    [DataContract]
        public partial class AppleCertificateSecretRequestData :  IEquatable<AppleCertificateSecretRequestData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AppleCertificateSecretRequestData" /> class.
        /// </summary>
        /// <param name="base64Certificate">The certificate contents in base 64 encoded string (required).</param>
        /// <param name="password">The password for the certificate (required).</param>
        public AppleCertificateSecretRequestData(string base64Certificate = default(string), string password = default(string))
        {
            // to ensure "base64Certificate" is required (not null)
            if (base64Certificate == null)
            {
                throw new InvalidDataException("base64Certificate is a required property for AppleCertificateSecretRequestData and cannot be null");
            }
            else
            {
                this.Base64Certificate = base64Certificate;
            }
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new InvalidDataException("password is a required property for AppleCertificateSecretRequestData and cannot be null");
            }
            else
            {
                this.Password = password;
            }
        }
        
        /// <summary>
        /// The certificate contents in base 64 encoded string
        /// </summary>
        /// <value>The certificate contents in base 64 encoded string</value>
        [DataMember(Name="base64Certificate", EmitDefaultValue=false)]
        public string Base64Certificate { get; set; }

        /// <summary>
        /// The password for the certificate
        /// </summary>
        /// <value>The password for the certificate</value>
        [DataMember(Name="password", EmitDefaultValue=false)]
        public string Password { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AppleCertificateSecretRequestData {\n");
            sb.Append("  Base64Certificate: ").Append(Base64Certificate).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AppleCertificateSecretRequestData);
        }

        /// <summary>
        /// Returns true if AppleCertificateSecretRequestData instances are equal
        /// </summary>
        /// <param name="input">Instance of AppleCertificateSecretRequestData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AppleCertificateSecretRequestData input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Base64Certificate == input.Base64Certificate ||
                    (this.Base64Certificate != null &&
                    this.Base64Certificate.Equals(input.Base64Certificate))
                ) && 
                (
                    this.Password == input.Password ||
                    (this.Password != null &&
                    this.Password.Equals(input.Password))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Base64Certificate != null)
                    hashCode = hashCode * 59 + this.Base64Certificate.GetHashCode();
                if (this.Password != null)
                    hashCode = hashCode * 59 + this.Password.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
