/* 
 * App Center Client
 *
 * Microsoft Visual Studio App Center API
 *
 * OpenAPI spec version: v0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = AppCenterApiClientLib.Client.SwaggerDateConverter;

namespace AppCenterApiClientLib.Model
{
    /// <summary>
    /// Audience with details.
    /// </summary>
    [DataContract]
        public partial class Audience :  IEquatable<Audience>, IValidatableObject
    {
        /// <summary>
        /// Defines Inner
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum InnerEnum
        {
            /// <summary>
            /// Enum String for value: string
            /// </summary>
            [EnumMember(Value = "string")]
            String = 1,
            /// <summary>
            /// Enum Number for value: number
            /// </summary>
            [EnumMember(Value = "number")]
            Number = 2,
            /// <summary>
            /// Enum Boolean for value: boolean
            /// </summary>
            [EnumMember(Value = "boolean")]
            Boolean = 3,
            /// <summary>
            /// Enum Datetime for value: date_time
            /// </summary>
            [EnumMember(Value = "date_time")]
            Datetime = 4        }
        /// <summary>
        /// Custom properties used in the definition.
        /// </summary>
        /// <value>Custom properties used in the definition.</value>
        [DataMember(Name="custom_properties", EmitDefaultValue=false)]
        public Dictionary<string, InnerEnum> CustomProperties { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Audience" /> class.
        /// </summary>
        /// <param name="enabled">enabled (default to true).</param>
        /// <param name="customProperties">Custom properties used in the definition..</param>
        /// <param name="estimatedTotalCount">Estimated total audience size..</param>
        /// <param name="timestamp">Date the audience was last refreshed..</param>
        public Audience(bool? enabled = true, Dictionary<string, InnerEnum> customProperties = default(Dictionary<string, InnerEnum>), long? estimatedTotalCount = default(long?), DateTime? timestamp = default(DateTime?))
        {
            // use default value if no "enabled" provided
            if (enabled == null)
            {
                this.Enabled = true;
            }
            else
            {
                this.Enabled = enabled;
            }
            this.CustomProperties = customProperties;
            this.EstimatedTotalCount = estimatedTotalCount;
            this.Timestamp = timestamp;
        }
        
        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [DataMember(Name="enabled", EmitDefaultValue=false)]
        public bool? Enabled { get; set; }


        /// <summary>
        /// Estimated total audience size.
        /// </summary>
        /// <value>Estimated total audience size.</value>
        [DataMember(Name="estimated_total_count", EmitDefaultValue=false)]
        public long? EstimatedTotalCount { get; set; }

        /// <summary>
        /// Date the audience was last refreshed.
        /// </summary>
        /// <value>Date the audience was last refreshed.</value>
        [DataMember(Name="timestamp", EmitDefaultValue=false)]
        public DateTime? Timestamp { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Audience {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("  CustomProperties: ").Append(CustomProperties).Append("\n");
            sb.Append("  EstimatedTotalCount: ").Append(EstimatedTotalCount).Append("\n");
            sb.Append("  Timestamp: ").Append(Timestamp).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Audience);
        }

        /// <summary>
        /// Returns true if Audience instances are equal
        /// </summary>
        /// <param name="input">Instance of Audience to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Audience input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Enabled == input.Enabled ||
                    (this.Enabled != null &&
                    this.Enabled.Equals(input.Enabled))
                ) && 
                (
                    this.CustomProperties == input.CustomProperties ||
                    this.CustomProperties != null &&
                    input.CustomProperties != null &&
                    this.CustomProperties.SequenceEqual(input.CustomProperties)
                ) && 
                (
                    this.EstimatedTotalCount == input.EstimatedTotalCount ||
                    (this.EstimatedTotalCount != null &&
                    this.EstimatedTotalCount.Equals(input.EstimatedTotalCount))
                ) && 
                (
                    this.Timestamp == input.Timestamp ||
                    (this.Timestamp != null &&
                    this.Timestamp.Equals(input.Timestamp))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Enabled != null)
                    hashCode = hashCode * 59 + this.Enabled.GetHashCode();
                if (this.CustomProperties != null)
                    hashCode = hashCode * 59 + this.CustomProperties.GetHashCode();
                if (this.EstimatedTotalCount != null)
                    hashCode = hashCode * 59 + this.EstimatedTotalCount.GetHashCode();
                if (this.Timestamp != null)
                    hashCode = hashCode * 59 + this.Timestamp.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
